### ISSUE TITLE
Tesla Solar Panels not selectable as Solar Production in Energy Config

### ISSUE THREAD

**Issue by qJake** [alandtse/tesla#107]
## Version of the custom_component

v1.3.2 (teslajsonpy 1.2.1)

## Describe the bug

We just enabled our solar panels today and I was excited to add the solar production to my Energy Dashboard in HA.

Unfortunately the solar panels don't show up as an energy source. 😞 

![image](https://user-images.githubusercontent.com/652006/144546073-dc26dbaf-7ae0-4de9-bbd8-c86201850b88.png)

I tried with just the out-of-the-box entity:

![image](https://user-images.githubusercontent.com/652006/144545938-0b3436d0-3c28-4573-8445-65f196a400c6.png)

As well as customizing some of the attributes to see if that was the issue:

![image](https://user-images.githubusercontent.com/652006/144545638-6340fc0d-c17f-4b84-b703-37555758d863.png)

(I tried lots of different combinations - state_class=measurement or total or total_increasing, UOM=W or kW or kWh, device_class=power or energy, including or excluding a last_reset attribute...)

Am I doing something wrong, or is this a bug? And - can I add any customizations/attributes to get it to work?

## Debug log

*This isn't an error, just a misconfiguration/issue with how Home Assistant reads energy entities, so there are no errors in any logs.*

**Comment by alandtse** [comment]
The Energy component requires that you use the integrate component to convert W to kwH. This is similar to our prior discussion on the energy_added sensor. https://github.com/alandtse/tesla/issues/14

**Comment by qJake** [comment]
@alandtse Gotcha - I thought at some point this component was updated to support those entity types out of the box. Might be a good enhancement for the future.

I'm pretty sure I can get it to work, if I run into any issues I'll reopen. Thanks for the guidance!

**Comment by alandtse** [comment]
At this point, it's probably a HA improvement to automatically create an integration sensor for power type sensors. We just expose what Tesla already has and unfortunately this is all we have.

**Comment by nicholashead** [comment]
@qJake mind sharing how you got this working? I added the kWh via the "integration" platform, but it never seems to reset and is showing higher and higher kWh:

![image](https://user-images.githubusercontent.com/1168659/145722846-70aaf469-096c-4bd2-b0c0-c12f698763f9.jpeg)

Here's my yaml:

  - platform: integration
    source: sensor.my_home_solar_panel
    name: tesla_solarpanels_kwh
    unit_prefix: k
    unit_time: h
    round: 2

**Comment by jbishop129** [comment]
For anyone else who might find this, I had to do this:

in my `configuration.yaml` 
create or add to the `homeassistant:` section:
```
homeassistant:
  customize:
    sensor.home_solar_panel:
      state_class: total
      device_class: energy
      unit_of_measurement: Wh
```
This overrides the default entity attributes, to format it so it fits the rules of [Long Term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics). I was fiddling a bunch, so I dont know if I needed to wait longer or not, but i noticed even after setting those overrides and restarting HA, the Statistics tab in Developer still showed the sensor as having the wrong units (W instead of Wh or kWh). I suspect that's because the sensor had already been built and established in the database. I deleted the Integration, deleted the entity, **and** deleted the long-term-statistics  from the Statistics tab (search for the entity, HA will tell you something about it being missing, and give you an option to clear the historical data)

After that, I reloaded the HACS Tesla integration, it came in with the right units (since the entity_id was identical and already had the `customize:` override described above), then it Just Worked!

Likely more fiddlig to do here, since I think I'll need to define a `last_reset` so the stats know that it resets to zero each night. 

Home this helps.
