### ISSUE TITLE
delete extra tesla device?

### ISSUE THREAD

**Issue by xac1d** [alandtse/tesla#141]
not sure if this is a HA issue or Tesla Custom integration issue but I have 2 tesla device entries and one has all the controls/sensors working fine, but another entry has nothing (no sensors, controls, etc).

how do i delete the other tesla entry?

**Comment by peerkn** [comment]
I have the same problem.

**Comment by alandtse** [comment]
It's probably a HA error as the Device registration code hasn't changed. Possibly it's caused by a HA migration. You can manually delete the Tesla devices from the device registry from `.storage/core.device_registry` and they'd get recreated by the component at the next restart.

**Comment by peerkn** [comment]
Thank you for the hint! It works. Best regards  Peer Gesendet von Mail für Windows Von: Alan TseGesendet: Sonntag, 6. Februar 2022 22:43An: alandtse/teslaCc: peerkn; CommentBetreff: Re: [alandtse/tesla] delete extra tesla device? (Issue #141) It's probably a HA error as the Device registration code hasn't changed. Possibly it's caused by a HA migration. You can manually delete the Tesla devices from the device registry from .storage/core.device_registry and they'd get recreated by the component at the next restart.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>
