### ISSUE TITLE
Please support Fahrenheit Temp Measures. 

### ISSUE THREAD

**Issue by hdprice** [alandtse/tesla#191]
Right now it seems that only Celsius is supported.

**Comment by alandtse** [comment]
This is controlled by the Tesla and HA UIs.
![image](https://user-images.githubusercontent.com/7086117/163771746-8a231d80-64aa-46ad-a9ad-390d90dde66d.png)

**Comment by muslimsteel** [comment]
## Version of the custom_component

2.0.1

## Configuration

```yaml
Add your logs here.
```
Installed via HACS, I am not sure where the logs are located.

## Describe the bug

A clear and concise description of what the bug is.
Since Home Assistant release 2022.4 (I am currently on 2022.4.5), the two temperature sensors (not the HVAC component as you showed above) are showing as Celsius where they were showing Fahrenheit before. One is for the inside temperature and one is for the outside temperature. 
![image](https://user-images.githubusercontent.com/28244480/164080379-0044c284-d105-427a-b557-ea7845cf127c.png)

I have checked and my global temperature setting is set to Imperial/Fahrenheit and since this release of Home Assistant they have allowed you to individually change the entity unit of measurement. I have tried to change that on both of these but nothing happens when I click Update, it just stays as Celsius and when you go back to the entity settings it is back to Celsius again.
![image](https://user-images.githubusercontent.com/28244480/164080810-934bd64c-e90c-49d3-b794-47319fc1b6c2.png)

I am happy to provide more information to help resolve this, just wanted to get more details on the information you need. Thanks.

## Debug log
Did you want specific component logs for this integration or did you want everything on debug level?

**Comment by alandtse** [comment]
Ok, I see it now. Looks like they changed something in HA.
