### ISSUE TITLE
solar power sensor unavailable 

### ISSUE THREAD

**Issue by ylwmamba** [alandtse/tesla#257]
## Version of the custom_component

v2.4.1

## Configuration

```yaml
logger:
  default: critical
  logs:
    custom_components.tesla_custom: debug
    teslajsonpy: debug
```

## Describe the bug

Solar power sensor unavailable, however still able to view history

![image](https://user-images.githubusercontent.com/99165322/187098379-40af32ec-592b-4c47-bcc5-b453bd4ddf5b.png)

![image](https://user-images.githubusercontent.com/99165322/187098387-e74f8c95-4141-49df-a3b5-2dfff293ea82.png)

## Debug log

```text

This error originated from a custom integration.

Logger: custom_components.tesla_custom
Source: custom_components/tesla_custom/__init__.py:288
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 4:03:59 PM (6 occurrences)
Last logged: 4:04:50 PM

Unexpected error fetching tesla_custom data: 'grid_status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla_custom/__init__.py", line 288, in _async_update_data
    return await self.controller.update()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1074, in update
    return any(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 991, in _get_and_process_energysite_data
    if response["grid_status"] == "Active":
KeyError: 'grid_status'


```

**Comment by shred86** [comment]
Hm. So that debug log is related to something else that was fixed in this [pull request](https://github.com/zabuldon/teslajsonpy/pull/346).

This is so odd because the solar panel sensor is being "created" exactly the same way as it was before. Are you able to access the `custom_components/tesla_custom` folder and edit some files? I'd like to throw a few more logger entries in the code to see what's going on. Sorry for the hassle, this one really has me stumped.

**Comment by ylwmamba** [comment]
Sure I can try to do that.

**Comment by shred86** [comment]
Okay, inside `custom_components/tesla_custom`, can you open the file `__init__.py` and add the following to line 207:

`_LOGGER.warning("Energysites: %s", coordinator.controller.energysites)`

So it should look like this with the existing code above and below:

````
    all_devices = controller.get_homeassistant_components()
    _LOGGER.warning("Energysites: %s", coordinator.controller.energysites)
    if not all_devices:
````

And open `sensor.py` and add the following two entries starting at line 40:

````
_LOGGER.warning("Sensor name: %s", self._name)
_LOGGER.warning("Sensor UUID: %s", self._unique_id)
````

It should look like this with the existing code above it:

````
        if self.type:
            self._name = f"{super().name} ({self.type})"
            self._unique_id = f"{super().unique_id}_{self.type}"
        _LOGGER.warning("Sensor name: %s", self._name)
        _LOGGER.warning("Sensor UUID: %s", self._unique_id)

````

Spacing is important so make sure the lines you're adding are lined up just like in the examples above with the existing code. Hopefully that makes sense.

Save and restart HA and this should show up in your logs as a warning. 

For the "Energysites: " log entry, if you can share that entire line and just remove any personal information like `energy_site_id`, `id`, etc., that would be very helpful.

There will likely be a lot of entries for the "Sensor name" and "Sensor UUID" since it will print out for each car sensor as well. I'm just interested in the one that should have `solar panel` in the name. There's probably going to be some numbers in the UUID, just change them to something else as this is your systems `energy_site_id` which is sort of "personal" info, although there's really nothing anyone can do with it.

**Comment by shred86** [comment]
Ah shoot, at the top of `sensor.py`, you'll have to add these lines:

````
import logging
_LOGGER = logging.getLogger(__name__)
````

So starting at line 2:
````
"""Support for Tesla cars."""
import logging
_LOGGER = logging.getLogger(__name__)
````

**Comment by shred86** [comment]
Here's an example of how the energysite entry will look. I put five X's for the information you can remove:
````
2022-08-29 00:06:07.138 WARNING (MainThread) [custom_components.tesla_custom] Energysites: [{'energy_site_id': XXXXX, 'resource_type': 'solar', 'id': 'XXXXX', 'asset_site_id': 'XXXXX', 'solar_power': 3570, 'solar_type': 'pv_panel', 'storm_mode_enabled': None, 'powerwall_onboarding_settings_set': None, 'sync_grid_alert_enabled': False, 'breaker_alert_enabled': False, 'components': {'solar': True, 'solar_type': 'pv_panel', 'battery': False, 'grid': True, 'backup': False, 'gateway': 'gateway_type_none', 'load_meter': True, 'tou_capable': False, 'storm_mode_capable': False, 'flex_energy_request_capable': False, 'car_charging_data_supported': False, 'off_grid_vehicle_charging_reserve_supported': False, 'vehicle_charging_performance_view_enabled': False, 'vehicle_charging_solar_offset_view_enabled': False, 'battery_solar_offset_view_enabled': False, 'energy_service_self_scheduling_enabled': True, 'configurable': False, 'grid_services_enabled': False}, 'site_name': 'My Home', 'site_number': 'STE20220404-00384', 'installation_date': '2022-04-04T15:56:35-07:00', 'user_settings': {'storm_mode_enabled': None, 'powerwall_onboarding_settings_set': None, 'sync_grid_alert_enabled': False, 'breaker_alert_enabled': False}, 'installation_time_zone': 'America/Los_Angeles', 'time_zone_offset': -420, 'geolocation': {'latitude': XXXXX, 'longitude': XXXXX}, 'address': {'address_line1': '1XXXXX', 'XXXXX', 'state': 'XXXXX', 'zip': 'XXXXX', 'country': 'US'}, 'grid_power': 0, 'load_power': 0}]
````

And for your solar panel sensor:

````
2022-08-29 00:06:07.418 WARNING (MainThread) [custom_components.tesla_custom.sensor] Sensor name: My Home solar panel
2022-08-29 00:06:07.420 WARNING (MainThread) [custom_components.tesla_custom.sensor] Sensor UUID: XXXXX_solar_panel
````

**Comment by shred86** [comment]
I forgot if you have debug logger set, which it looks like you do, you should already have some of this data (at least for energy sites) if you search for this in your logs:

`[teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/products {}`

The very next entry will be the response that should have your car and solar site information. If you just copy starting from the end until `{"energy_site_id`, I can start with that. Sorry I should have had you start with this step.

**Comment by ylwmamba** [comment]
I have 2 new logs now in addition to the previous one:

This error originated from a custom integration.

Logger: custom_components.tesla_custom.sensor
Source: custom_components/tesla_custom/sensor.py:27
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 6:37:04 PM (2 occurrences)
Last logged: 6:37:04 PM

Sensor name: My Home solar panel
Sensor UUID: XXXX_solar_panel


2nd one is:

This error originated from a custom integration.

Logger: custom_components.tesla_custom
Source: custom_components/tesla_custom/__init__.py:207
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 6:37:04 PM (1 occurrences)
Last logged: 6:37:04 PM

Energysites: [{'XXXX, 'resource_type': 'solar', 'site_name': 'My Home', 'id': 'a2450bcd-570d-40e3-8ee4-a7ef03701c32', 'asset_site_id': '22e9ab3a-a9aa-425b-9ef8-a14ebc939a2c', 'solar_power': 480, 'solar_type': 'pv_panel', 'storm_mode_enabled': None, 'powerwall_onboarding_settings_set': None, 'sync_grid_alert_enabled': False, 'breaker_alert_enabled': False, 'components': {'solar': True, 'solar_type': 'pv_panel', 'battery': False, 'grid': True, 'backup': False, 'gateway': 'neo', 'load_meter': False, 'tou_capable': False, 'storm_mode_capable': False, 'flex_energy_request_capable': False, 'car_charging_data_supported': False, 'off_grid_vehicle_charging_reserve_supported': False, 'vehicle_charging_performance_view_enabled': False, 'vehicle_charging_solar_offset_view_enabled': False, 'battery_solar_offset_view_enabled': False, 'energy_service_self_scheduling_enabled': True, 'configurable': False, 'grid_services_enabled': False}, 'site_number': 'STE20180524-06207', 'installation_date': '2021-07-27T17:00:00-07:00', 'user_settings': {'storm_mode_enabled': None, 'powerwall_onboarding_settings_set': None, 'sync_grid_alert_enabled': False, 'breaker_alert_enabled': False}, 'time_zone_offset': -420, 'geolocation': {'latitude': XX, 'longitude': -XX}, 'address': {'XXXX'}, 'grid_power': 0, 'load_power': 0}]

**Comment by shred86** [comment]
Okay, that is strange. It's definitely creating the sensor so the question is, why isn't it showing up.

If you look at the Tesla Custom Integration under Settings > Devices & Services, is it showing "2 devices"? One for your car (assuming you have one) and one for the solar site?

On that same page, if you click Entities at the top and search for "solar", do you see the sensor at all? It should be titled "My Home solar panel".

**Comment by ylwmamba** [comment]
The sensor is being created. I actually don't have a car, just the panels.

![image](https://user-images.githubusercontent.com/99165322/187116710-abbe467c-b961-45f2-8b3c-d8d142db3bbe.png)

![image](https://user-images.githubusercontent.com/99165322/187116745-f8cd17e0-b2d3-4ef7-91f9-6adc958093a8.png)

**Comment by shred86** [comment]
Ah okay - I wasn't sure if that was just left over from the previous integration version. So I take back what I said in my first post. I think what's happening is based on the KeyError, which is occurring during an update to the Tesla API, it's terminating that part of the code so the sensor never gets any valid data back, hence the "Unavailable". I already have a [pull request](https://github.com/zabuldon/teslajsonpy/pull/346) open to fix that issue in teslajsonpy (the library that this integration uses), so as soon as it's merged I'll create a pull request here to bump the version. Hopefully it will only be a day or two before it's released.

As a side note, was the previous version working okay in terms of update rates? Were you seeing the solar panel sensor update about every 10 seconds? I thought I found an issue where if you don't have a car, I thought the solar stuff didn't update but you're the first person I've found that could verify this.

**Comment by ylwmamba** [comment]
So I was reviewing the history and it looks like it was being updated relatively frequently. I didn't necessarily check to see how often it was. Here is a closer look at the history from today. Surprisingly there are still some data points showing after I updated (around 4 PM).

![image](https://user-images.githubusercontent.com/99165322/187119676-a69f0eae-2217-47e1-8a25-3fcd0af4ba84.png)

**Comment by shred86** [comment]
Ah okay, that's good to know it still works without a car on the account.

Yeah, I think that makes sense you're seeing random data points. It appears the Tesla API endpoint we use, `live_data` aka `SITE_DATA` will sometimes report `grid_status` and sometimes it won't. There's another user that identified an issue with his setup, which I think is similar to yours (solar only with a Neo 2 gateway), where sometimes Tesla's servers will report a `grid_status` of `Unknown` with spurious `solar_power` readings of `0`. Based on that, a check was added to disregard the readings when that happens but then there's other users like me (Tesla solar only with a Tesla inverter) and `grid_status` is always `Unknown`, so we're always tripping that check that was added when there's no solar generation (e.g. night) which causes problems for us.

I added an additional check in hopes to provide a solution for both cases but that's where I discovered `grid_status` doesn't appear to be in the Tesla API response all the time so that's what's causing this KeyError and likely this issue you're seeing. Hopefully the changes will be merged tomorrow and this issue will be fixed. Sorry for the hassle - we're learning as we go with the various solar setups.

**Comment by shred86** [comment]
@ylwmamba Version 2.4.2 is out so please give that a shot and let me know if it does or does not fix the issue.

**Comment by ylwmamba** [comment]
> @ylwmamba Version 2.4.2 is out so please give that a shot and let me know if it does or does not fix the issue.

It looks like this may have fixed the issue. It's no longer showing unavailable and nothing showing up on the logs. I'll take a look tomorrow to see if the data is coming through. Thanks for all the hard work!

![image](https://user-images.githubusercontent.com/99165322/187338170-4ee69367-facc-401f-bc83-a64b8f875f0e.png)
