### ISSUE TITLE
binary_sensor.<car>_asleep

### ISSUE THREAD

**Issue by carleeno** [alandtse/tesla#360]
**Is your feature request related to a problem? Please describe.**
I'm unable to determine if car is disconnected (poor signal, service outage) vs asleep

**Describe the solution you'd like**
A binary sensor to indicate if the car is asleep

**Describe alternatives you've considered**
- An attribute to the online sensor that shows state: asleep (this is what v2.* of the tesla integration had). The attribute worked, but having a dedicated binary sensor is much more useful given how often/common it is for the car to be asleep vs offline.
- Change the online binary_sensor to a regular sensor and publish the different states. this would be too disruptive to change an existing sensor.

**Additional context**
I'm happy to make a PR (here and in teslajsonpy) to add the asleep binary sensor, but I wanted to started a conversation first to see if we feel that's the best approach.

**Comment by alandtse** [comment]
@shred86 any thoughts since you were the one to change it?

I'm ok with an added attribute although the HA philosophy was to move away from attributes and move to straight sensors. I believe the philosophy is that anything someone may want to access directly or have history of, should be it's own sensor.

Breaking changes are highly disruptive so the preference is to avoid them unless there's a strong justification. That would mean we should lean to keeping existing sensors functional and adding others. Of course, that may mean we end up with tons of sensors so that's another countervailing issue to consider.

**Comment by carleeno** [comment]
thanks @alandtse that's what I was feeling as well, which is why my main solution/suggestion was to add a new sensor for it. Apologies if I didn't format the request well.

**Comment by alandtse** [comment]
Oh sorry. Most people aren't using the template so I forgot that the alternatives section existed and I just answered without thinking. Yes, I'm fine with a binary sensor PR.
