### ISSUE TITLE
Window cover icons are counterintuitive

### ISSUE THREAD

**Issue by FalconUK** [alandtse/tesla#394]
The new windows cover has been added, which is great, but the up arrow icon is used for 'Open cover', and the down arrow icon is used for 'Close cover', which is counterintuitive.

**Comment by MitchellHayes** [comment]
I totally agree with this, I am hoping to get involved with working on this integration, so let me see if I can get this one taken care of.

**Comment by MitchellHayes** [comment]
So far it looks like we are stuck using the Home Assistant Cover Device Classes. They bring over different buttons based on the class and I don't see a way to change those. We could switch to the device class awning, which is odd considering it's a window, but it would create a button similar to the trunk buttons. Unfortunately, there isn't a good device class to use for car windows. 
![image](https://user-images.githubusercontent.com/1672071/205518823-187bed12-15eb-49e0-aded-cb18803f9d4b.png)

**Comment by carleeno** [comment]
It might be possible to manually set the open/close icons in the component by overriding the base entity icon attributes, but I'm failing to find which attributes to set for that, if they exist at all.

If not it might be worth reaching out to HA to see if that could be made configurable, otherwise you'd have to use a custom card to manually set the icons in your own instance: https://community.home-assistant.io/t/change-icon-for-cover-open-and-closed/158038

**Comment by MitchellHayes** [comment]
I don’t believe it’s currently an editable attribute. We can put a feature request in and see what happens. I believe the awning icons may be a bit more intuitive if we want to go that route. I second editing the card on your personal instance for use on your dashboards. Not sure who would make a final call on the device class.

**Comment by alandtse** [comment]
I think the inverted nature is what stalled this in the original PR. We should raise the issue with HA but realize that any change in HA will take a year or so to happen given their PR backlog. So what we can probably do is:

1. Choose a cover with the right arrows.
2. Force the icon to use one that works for a car.
3. Submit a PR to HA adding a car window device class with the chosen icon. Potentially ping other car integration codeowners to get their buy in on the new cover. (I guess we could also look at their integrations too to see what they did for windows...)

**Comment by MitchellHayes** [comment]
I can do just that. I will get it switched to the Awning Device Class since that arrow set matches, and set the icon to clearly be a car door window. Once I get that submitted I will get a PR to HA for adding a car window Device Class. I looked at some other car integrations but didn't see any that allowed opening windows.
