### ISSUE TITLE
sensor.vehicle_energy_added wrongly counting when resuming charging

### ISSUE THREAD

**Issue by evolucja** [alandtse/tesla#413]
![image](https://user-images.githubusercontent.com/990929/206454345-ae0bc0c0-d65c-4758-a66d-70fdb48615cd.png)

Hi, it looks like when we stop charging and then start it again (or when it reached certain percentage and then we increase the percentage so it starts charging again without starting the new session) the counter doesn't start from 0 but from the last value so using it for energy meters can double or triple the charged kWh amount.

Any idea how to fix that?

**Comment by evolucja** [comment]
Unfortunately, it still doesn't work with 3.7.0. The car was charged last a few days ago. Since then it counted energy added 5 times.

![image](https://user-images.githubusercontent.com/990929/208134205-bfd2dc7f-c42c-4af1-9fe8-5efb84911738.png)

**Comment by carleeno** [comment]
@evolucja can you share the same history time range of the
- charging sensor
- charger sensor
- online sensor
- alseep sensor

we need to correlate when it is going to 0 to try to figure out why it's doing that. I double checked the code and we're not manually setting 0 for that sensor anywhere in the code so now I'm wondering if the car is reporting 0 sometimes.

**Comment by evolucja** [comment]
@carleeno here it is:

![image](https://user-images.githubusercontent.com/990929/208141709-11c72e43-fe79-4578-a560-2eeca43a47a3.png)

**Comment by carleeno** [comment]
@evolucja almost, it's supposed to reset the energy added value when charger goes from 0 to 1, and retain that value when the charger goes from 1 to 0. Here's mine so you can see what it's supposed to look like
![image](https://user-images.githubusercontent.com/54586926/208221727-35f3411d-8113-4b18-a24b-a656c72a215d.png)

it looks like when you unplug the charger and plug it back in, it's resetting to 0, but then you never charge and unplug it again, and since it never charged it reset to the previous energy added value. I'll try to replicate this with my car by stopping the charge, unplugging, plugging back in, and unplugging before it charges again.

Note the data you are seeing is directly coming from Tesla's api, we are no longer manipulating the value. If there is a value available, we give it; if there is no data available, it shows as `unknown`...so I'm not sure there is anything we can do about this behavior if tesla is resetting the value to 0 and then back to the previous value. Maybe you can also help verify this with debug logs and try to reproduce using the same steps, recording the data json each time.

**Comment by evolucja** [comment]
Hmm don't know what happened but it normalized after the newest update and so far looks good...

![image](https://user-images.githubusercontent.com/990929/209863779-7b2af237-473d-4e21-b25e-857d50fe96af.png)
