### ISSUE TITLE
Window sensors?

### ISSUE THREAD

**Issue by bkr1969** [alandtse/tesla#641]
Version 3.14.0

## Describe the bug

The new binary sensors for window do not change when widows are vented until car is woken up.  Why is venting the windows not sufficient to update the sensor?

## Debug log

There is nothing to add from the logs as the sensors change but only upon awakening vehicle.

**Comment by alandtse** [comment]
@ileodo can you take a look please? Perhaps it's only certain vehicles that can access this?

**Comment by alandtse** [comment]
Actually this could be this. https://github.com/alandtse/tesla/wiki/Polling-policy

**Comment by bkr1969** [comment]
That makes sense.  Unfortunately it also makes them less useful for my purposes.  I monitor the cabin temp at work and if it reaches 90 and it's less than that outside, the windows vent automatically.  The problem is that if they're vented and it becomes rainy, the state needs to be readily available so they can close.  I will just stick with the input_boolean I created that tracks when they open/close.

**Comment by alandtse** [comment]
Are you venting via the Tesla App or via the component? The component should be updating it if it's making the request. If it isn't, that's a bug. However, if you're doing it somewhere else, there really is no way for the component to know. It only knows about changes due to a poll and the polling has to be conservative to avoid vampire drain.
