### ISSUE TITLE
Destination location tracker unknown

### ISSUE THREAD

**Issue by BliXem1** [alandtse/tesla#787]
Hi,

Since the new update of Tesla, the Destination location tracker is unknown, also the location tracker is unknown. Is there a way how I can fix this?

Home settings are already setup within HA.

**Comment by skipishere** [comment]
When raising an issue please follow the template that asks for the version of the extension and other information. From the limited information this seems like a duplicate of either the location issue that had been fixed in latest or issues with the API.

For now I'll close this as duplicate but happy to reopen when more information is supplied

**Comment by BliXem1** [comment]
HA version: 2023.11.3

**Version of the custom_component:**

3.19.3

**Configuration:**

Running HA with HACS, no other special configuration.

Is this enough info, if not, let me know.
Got no special errors, but it stays on unknown, so dunno what to do now. This is a few weeks already.

**Comment by skipishere** [comment]
Ideally the more information you can tell us the more hope we have of looking into it/possibly fixing it. For example I'm also on 3.19.3 and this fixed the location issue that occurred when my car updated 3-4 weeks ago to the latest Model 3 firmware (2023.38.6) that changed the way location sharing worked.

Couple of things:

- Have you restarted Home Assistant since updating to 3.19.3
- What version of firmware is your car on (& what model)?
- Do any of the commands work?
- Are any other sensors not updating/unknown?

**Comment by BliXem1** [comment]
**Have you restarted Home Assistant since updating to 3.19.3**

Yes, many times.

**What version of firmware is your car on (& what model)?**

Firmware Tesla: 2023.38.6
Model: Y RWD

**Do any of the commands work?**

Yes, everything does work. If I open the windows, climate on, etc.

**Are any other sensors not updating/unknown?**
Got three:
Arrival time
Destination location tracker
Location tracker

If I check the logbook of destination location tracker I see this:

is at unknown
09:29:33 - 42 minuten geleden
is at unavailable
09:29:20 - 43 minuten geleden

All three on unknown. I don't see any logs of the custom component.
Maybe I need to delete the component and re-install?

**Comment by skipishere** [comment]
Does seem a bit odd. 
Reinstall is probably worth a shot, if that fails would be great if you could see what's in the logs and see if there's any useful info in them.

**Comment by alandtse** [comment]
We'll also need some [debug logs](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics). It would tell us if the api calls are failing.

**Comment by BliXem1** [comment]
Do I need to turn something on in the car for location access via API?

**Comment by BliXem1** [comment]
![Uploading Schermafbeelding 2023-11-28 105136.png…]()

**Comment by BliXem1** [comment]
Any news?

**Comment by baylanger** [comment]
> Do I need to turn something on in the car for location access via API?

Make sure “privacy share data” is enable. this tells your vehicle to publish your private data to Tesla.

**Comment by baylanger** [comment]
> Do I need to turn something on in the car for location access via API?

From T website , check if things are enable.

Tesla enables you to control what you share. Within your vehicle’s touchscreen you may enable or disable the collection of certain vehicle data (Software > Data Sharing), including Autopilot Analytics & Improvements and Road Segment Data Analytics.


You could also try a reset and see if that helps : Controls > Service > Factory Reset

**Comment by baylanger** [comment]
Not sure when this was introduced but it sure is in latest carOS version.

![IMG_2595](https://github.com/alandtse/tesla/assets/5240348/3aedbc5d-9c52-4942-a5da-fef210451ffe)

**Comment by Henke19822** [comment]
I have the same struggles since 2023.38.9 update on my Model Y. Will continue troubleshooting but this far it seems directly connected with the car update

**Comment by BliXem1** [comment]
Checked everything but "Mobile connection" is on. Can't change much else. Still no luck.

**Comment by BliXem1** [comment]
I did before the 2 latest versions. Everything did worked perfectly. After the update not anymore :(

**Comment by skipishere** [comment]
> So, I've never been able to get any data from the location tracker, nor the destination location tracker. I've checked all privacy settings in the vehicle but all seems Ok there. Does anyone actually see data from the location tracker?

It works for lots of us, as you can see below, it comes with some decent amount of data and works with the HA zones. If you've got additional information that would help us diagnose why you aren't getting that information than people might be able to look into it/debug it. Otherwise there isn't much we can do (as it "works on my machine" as they say 😅)
![image](https://github.com/alandtse/tesla/assets/26724777/c6573984-072b-451f-8a1a-33c1fe711af7)

**Comment by BliXem1** [comment]
OK thnx for your reply.

**Comment by Henke19822** [comment]
> > I have the same struggles since 2023.38.9 update on my Model Y. Will continue troubleshooting but this far it seems directly connected with the car update
> 
> did you do a factory reset of the car?

Hi. No, I would really like to avoid that. I would rather live without a functioning location tracker to be honest, eventhough I have a bunch of automations connected to that feature.
Have checked everything in the car but nothing has changed.

**Comment by dtpanic** [comment]
I don't use this specific application, but I do have my own custom scripts that call the following API endpoint to get car location: 

https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/vehicle_data

Until recently, this worked. It returned JSON data including 'drive_state', which provided current vehicle lat/long.

However within the last week or so, this API endpoint stopped returning lat/long. Is this the API endpoint your app is using?

**Comment by pandahej** [comment]
Im having the same issue as [BliXem1](https://github.com/BliXem1). Worked fine until about 3 weeks ago when it stopped working. Have not updated or installed anything before that or since then.

I have removed the device and installed it again. 

 Home Assistant 2023.4.6 
 Supervisor 2023.11.6 
 Operating System 10.1 
 Frontend 20230411.1 - latest

**Comment by alandtse** [comment]
> I've confirmed that Tesla's API changed. You now have to pass additional arguments in the request to retrieve location information:

If you add a PR to [teslajsonpy](https://github.com/zabuldon/teslajsonpy) I'll go ahead and merge it if you ping tag me.

**Comment by SeBsZ** [comment]
I'm confused, these additional arguments are already added in teslajsonpy 3.9.7 and 3.9.8, which alandtse/tesla 3.19.3 uses. So this shouldn't be an issue anymore. (https://github.com/zabuldon/teslajsonpy/commit/0fb4ef0dd4a56e887b780794b47714e6bb57475e)

**Comment by Dan4096** [comment]
> I've confirmed that Tesla's API changed. You now have to pass additional arguments in the request to retrieve location information:
> 
> https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/vehicle_data?endpoints=location_data;charge_state

Hi, I have the same issue as reported, I went to that link for the Tesla API but it just shows a blank page. I'm already logged into my Tesla account. Unsure what I need to do to get that to work, could you assist please?

**Comment by skipishere** [comment]
> > I've confirmed that Tesla's API changed. You now have to pass additional arguments in the request to retrieve location information:
> > 
> > https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/vehicle_data?endpoints=location_data;charge_state
> 
> Hi, I have the same issue as reported, I went to that link for the Tesla API but it just shows a blank page. I'm already logged into my Tesla account. Unsure what I need to do to get that to work, could you assist please?

Hi Dan,

With no information or context we really have no idea how to help you.
As you may have seen in the thread it works for some of us and there have been a handful of people it doesn't work for. If your car is new or you've not used the Tesla app in the recent past then you might be in the situation where the old API isn't available to you. If that is the case there is already an issue raised about using the newer API.

**Comment by pradaker** [comment]
I was using this custom integration for several months, but like several other people in this thread, ever since Tesla introduced the new location sharing icon in the car's software, location tracking isn't working in this custom integration since doing so now requires the new way of allowing access to one's Tesla account.

I've noticed several other apps I previously signed in with my Tesla account are now requiring me to use the new Tesla "third party apps" feature for giving access to my account.

I'm not sure how @skipishere is still able to track location without doing that because Tesla should be restricting access.

Please fix this because I have several automations that relied on my car's location, and for now I'm instead having to use my phone's location, which drains my phone's battery.

**Comment by alandtse** [comment]
> Please fix this because I have several automations that relied on my car's location, and for now I'm instead having to use my phone's location, which drains my phone's battery.

Before this gets out of hand, this is a community effort. The source code is open and so far no one has offered any PR--much less anyone demanding a fix. 

The company that took your money has closed unofficial access to their API. Demanding volunteers for a free project to access that API is not helpful. If you need to redirect your frustration, the more appropriate outlet is to demand Tesla to reopen the API. But good luck with that. 

I can't speak for others, but I don't intend to start a business surviving on donations to register with Tesla for an official API. One, because I don't need another job and two, there is no way donations will cover the costs. It's not rational to expect that. 

If someone else wants to enable access, I will continue to manage the project. But given the nature of the requests here, actual history, and the effort involved, I'm not sure anyone wants to volunteer.

**Comment by pradaker** [comment]
> > Please fix this because I have several automations that relied on my car's location, and for now I'm instead having to use my phone's location, which drains my phone's battery.
> 
> Before this gets out of hand, this is a community effort. The source code is open and so far no one has offered any PR--much less anyone demanding a fix.
> 
> The company that took your money has closed unofficial access to their API. Demanding volunteers for a free project to access that API is not helpful. If you need to redirect your frustration, the more appropriate outlet is to demand Tesla to reopen the API. But good luck with that.
> 
> I can't speak for others, but I don't intend to start a business surviving on donations to register with Tesla for an official API. One, because I don't need another job and two, there is no way donations will cover the costs. It's not rational to expect that.
> 
> If someone else wants to enable access, I will continue to manage the project. But given the nature of the requests here, actual history, and the effort involved, I'm not sure anyone wants to volunteer.

You’re totally right. I’m sorry.

For anyone having this issue, I deleted my account (aka “Integration Entry” and added it again, but still had the same issue. However, I did it again a couple months later and location tracking seems to be working now.

So, maybe just try signing into your account again, and if that doesn’t work, try it again. Very bizarre, but at least it’s working for me again.

**Comment by Verguldebarman** [comment]
Same problem here, for some time already (weeks/months?), but did not notice until yesterday.
Tried removing/adding the integration as per the advice of @pradaker , but that did not do the trick.

HA Core 2023.12.4
HA Frontend 20231208.2
Tesla Custom version:  3.15.1

**Comment by BliXem1** [comment]
I reinstalled Home assistant and now it's working again.
