### ISSUE TITLE
Powerwall 2 backup reserve modification

### ISSUE THREAD

**Issue by unbroken75** [alandtse/tesla#819]
Since in winter my solar production is insufficient to cover load and fully recharge the battery, I would like to programmatically change my powerwall backup reserve so that the battery works mostly in the range 30%-70%. For example I would set it to:
- december: 35%
- november/january: 30%
- october/february: 20%
- rest of the year 10%

The power backup reserve can be set in the Tesla app, in the setting menu, so should be writable with this integration too, and changed through automation.
Is it possible to add this feature ?

Thank you very much.

**Comment by skipishere** [comment]
Power reserve is available to alter via Automations, so that might help you most of the way.

I have an extra 2 helpers, one for discharge down to and one for charge up to (as I have peak export and off peak import where I want to maximize my grid balancing/costs.
![image](https://github.com/alandtse/tesla/assets/26724777/18daab1b-65d2-4cc8-80b9-af73aee08ba9)

Happy to go into detail more if needed, but ultimately depending on the current battery % vs the export/import helper I alter my Powerwall to allow or disallow charging/exporting to the grid (this also needs the powerwall to have correct prices set so that it behaves in the correct way)

**Comment by unbroken75** [comment]
Sorry, didn't realize it's already a feature. I only read in the description that backup reserve is listed as a sensor, not a control.
Now I'm just concerned about whether the integration stops working: [https://github.com/alandtse/tesla/issues/743](url)
Thank you very much for sharing your use case.
