### ISSUE TITLE
[Feature request] When device state is unknown, fall back to last known state

### ISSUE THREAD

**Issue by Jay2645** [alandtse/tesla#99]
**Is your feature request related to a problem? Please describe.**
Sometimes my Model 3's "energy added" sensor can become unknown if the car can't be reached. This gives an annoying warning in the Energy configuration page:
![image](https://user-images.githubusercontent.com/2058763/141663843-359e9c96-e9ef-4de5-8c84-a5130044ca26.png)

**Describe the solution you'd like**
It would be nice if in these situations, it just read back the last known state, potentially with an attribute saying the state may be stale.

**Comment by alandtse** [comment]
I'll think about this. If we haven't contacted the car, we don't have any idea what the value was. This is actually probably the correct behavior. HA could add an option to ignore or snooze the result.

**Comment by Olen** [comment]
I have seen the sensors turn to unknown if polling fails for a short time (e.g. the Tesla API returns an error message). But I think that is more of a problem with telsajsonpy than with this integration.

**Comment by steve28** [comment]
yeah, this seems to be an issue if I restart HA - all of the sensors are unknown and then my automations fail (for example if have one that checks if it's 9p, Bothe myself the car are home, and it's not plugged in then it sends me a push notification.   If the device tracker is "unknown" then I get an error

**Comment by alandtse** [comment]
Your automations either need to handle the unknown state case or if you wanted to wake the cars to get the data on reboot, just turn on the option to wake them.
![image](https://user-images.githubusercontent.com/7086117/148705510-92bf33cf-1713-4ece-ab82-0e2e550fae1a.png)

Regardless, the proper response per HA is to return unknown when the data can't be accessed (unless there's an architecture document explaining otherwise). Failure to process unknown is a downstream problem.
